# lextab.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.2'
_lextokens    = {'LNOT': 1, 'RSHIFT': 1, 'RSHIFTEQUAL': 1, 'VOID': 1, 'NUMBER': 1, 'LOR': 1, 'WHILE': 1, 'DIVEQUAL': 1, 'LSHIFT': 1, 'MINUS': 1, 'RBRACE': 1, 'LAND': 1, 'RPAREN': 1, 'COLON': 1, 'MODEQUAL': 1, 'NE': 1, 'LT': 1, 'BREAKOUT': 1, 'PLUS': 1, 'COMMA': 1, 'LSHIFTEQUAL': 1, 'GT': 1, 'XOR': 1, 'DIVIDE': 1, 'PLUSPLUS': 1, 'EQUALS': 1, 'PERIOD': 1, 'ELSE': 1, 'PLUSEQUAL': 1, 'GE': 1, 'LE': 1, 'LPAREN': 1, 'MINUSMINUS': 1, 'TIMES': 1, 'EQ': 1, 'RBRACKET': 1, 'IF': 1, 'AND': 1, 'LBRACKET': 1, 'LBRACE': 1, 'NAME': 1, 'MINUSEQUAL': 1, 'XOREQUAL': 1, 'CONTINUE': 1, 'NOT': 1, 'ANDEQUAL': 1, 'OREQUAL': 1, 'OUT': 1, 'TIMESEQUAL': 1, 'OR': 1, 'MOD': 1}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [("(?P<t_NUMBER>\\d+)|(?P<t_newline>\\n+)|(?P<t_comment>/\\*(.|\\n)*?\\*/)|(?P<t_NAME>[a-zA-Z_][a-zA-Z0-9_]*[\\']*)|(?P<t_PLUSPLUS>\\+\\+)|(?P<t_LOR>\\|\\|)|(?P<t_RSHIFTEQUAL>>>=)|(?P<t_TIMESEQUAL>\\*=)|(?P<t_LSHIFTEQUAL><<=)|(?P<t_OREQUAL>\\|=)|(?P<t_PLUSEQUAL>\\+=)|(?P<t_XOREQUAL>^=)|(?P<t_LE><=)|(?P<t_RSHIFT>>>)|(?P<t_NE>!=)|(?P<t_PLUS>\\+)|(?P<t_RBRACE>\\})|(?P<t_MINUSEQUAL>-=)|(?P<t_EQ>==)|(?P<t_MINUSMINUS>--)|(?P<t_MODEQUAL>%=)|(?P<t_LPAREN>\\()|(?P<t_OR>\\|)|(?P<t_LBRACE>\\{)|(?P<t_PERIOD>\\.)|(?P<t_DIVEQUAL>/=)|(?P<t_XOR>\\^)|(?P<t_RBRACKET>\\])|(?P<t_LBRACKET>\\[)|(?P<t_GE>>=)|(?P<t_RPAREN>\\))|(?P<t_LAND>&&)|(?P<t_LSHIFT><<)|(?P<t_ANDEQUAL>&=)|(?P<t_TIMES>\\*)|(?P<t_AND>&)|(?P<t_NOT>~)|(?P<t_COMMA>,)|(?P<t_DIVIDE>/)|(?P<t_LT><)|(?P<t_MINUS>-)|(?P<t_MOD>%)|(?P<t_EQUALS>=)|(?P<t_COLON>:)|(?P<t_LNOT>!)|(?P<t_GT>>)", [None, ('t_NUMBER', 'NUMBER'), ('t_newline', 'newline'), ('t_comment', 'comment'), None, (None, 'NAME'), (None, 'PLUSPLUS'), (None, 'LOR'), (None, 'RSHIFTEQUAL'), (None, 'TIMESEQUAL'), (None, 'LSHIFTEQUAL'), (None, 'OREQUAL'), (None, 'PLUSEQUAL'), (None, 'XOREQUAL'), (None, 'LE'), (None, 'RSHIFT'), (None, 'NE'), (None, 'PLUS'), (None, 'RBRACE'), (None, 'MINUSEQUAL'), (None, 'EQ'), (None, 'MINUSMINUS'), (None, 'MODEQUAL'), (None, 'LPAREN'), (None, 'OR'), (None, 'LBRACE'), (None, 'PERIOD'), (None, 'DIVEQUAL'), (None, 'XOR'), (None, 'RBRACKET'), (None, 'LBRACKET'), (None, 'GE'), (None, 'RPAREN'), (None, 'LAND'), (None, 'LSHIFT'), (None, 'ANDEQUAL'), (None, 'TIMES'), (None, 'AND'), (None, 'NOT'), (None, 'COMMA'), (None, 'DIVIDE'), (None, 'LT'), (None, 'MINUS'), (None, 'MOD'), (None, 'EQUALS'), (None, 'COLON'), (None, 'LNOT'), (None, 'GT')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
